import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786309857633 implements MigrationInterface {
    name = 'InitialSchema1786309857633'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "phone" character varying, "passwordHash" character varying, "role" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "initials" character varying, "avatarBg" character varying, "avatarColor" character varying, "schoolId" uuid, "status" character varying NOT NULL DEFAULT 'active', "inviteCode" character varying, "otpCode" character varying, "otpExpiresAt" TIMESTAMP, "passwordResetOtp" character varying, "passwordResetOtpExpiresAt" TIMESTAMP, "passwordResetOtpAttempts" integer NOT NULL DEFAULT '0', "rememberToken" character varying, "resetToken" character varying, "resetTokenExpiresAt" TIMESTAMP, "themePreference" character varying NOT NULL DEFAULT 'system', "lastActiveAt" TIMESTAMP, "lastLoginAt" TIMESTAMP, "acceptedTermsAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_bbb81d30f7992d6cb1e328e7dd9" UNIQUE ("inviteCode"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "curriculumVersionId" uuid NOT NULL, "order" integer NOT NULL, "title" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'locked', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a8f2f064919b587d93936cb223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sync_queue" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "teacherId" uuid NOT NULL, "entityType" character varying, "entityId" character varying, "fileSizeKb" integer, "description" character varying, "attempts" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'queued', "queuedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ff45aae31ec336e210e9bb34e6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "schools" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "region" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "curriculumVersionId" uuid, "lastSyncAt" TIMESTAMP, "timezone" character varying, "academicYear" character varying, "currentTerm" character varying, "subject" character varying, "aiCapUsedPercent" numeric NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95b932e47ac129dd8e23a0db548" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "school_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "type" character varying NOT NULL, "term" character varying, "data" text, "generatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4bdaca45270bff2883d6e623536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "lessonId" uuid, "learnerId" uuid NOT NULL, "fileType" character varying NOT NULL, "fileName" character varying, "fileUrl" character varying, "codeSnippet" text, "description" text, "skills" text, "term" character varying, "gradientStyle" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "progress_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "childId" uuid NOT NULL, "term" character varying, "programme" character varying, "status" character varying NOT NULL DEFAULT 'draft', "reviewedBy" character varying, "reviewedByRole" character varying, "whatWentWell" text, "skillsGrowing" text, "nextSteps" text, "generatedBy" character varying, "publishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_175179020a43d5ec75ab1d6a04f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "parent_children" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parentId" uuid NOT NULL, "childId" uuid NOT NULL, "verificationStatus" character varying NOT NULL DEFAULT 'unverified', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fa75fd4cb16c624d01896f25db4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying, "title" character varying, "body" text, "relatedEntityId" character varying, "read" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media_library" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "fileName" character varying, "unitId" uuid, "uploadedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c023f8b633f4c4d6ea61bc4950" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lqs_scores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "learnerId" uuid NOT NULL, "lessonId" uuid, "dimensionId" uuid NOT NULL, "score" integer NOT NULL, "term" character varying, "savedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5207c0eaec9524ad067cf3eac37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lqs_dimensions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "color" character varying, "weight" numeric NOT NULL DEFAULT '1', "rubricVersion" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_68d7875b1512fe270d982128e75" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "unitId" uuid NOT NULL, "order" integer NOT NULL, "title" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'locked', "programme" character varying, "gradeLevel" character varying, "term" character varying, "week" character varying, "missionNumber" character varying, "durationMinutes" integer, "theme" character varying, "realWorldProblem" text, "bigIdea" text, "essentialQuestion" text, "learningOutcomes" text, "successCriteria" text, "keyVocabulary" text, "nerdcTheme" character varying, "nerdcTopic" character varying, "nerdcObjectives" text, "inputComponent" text, "brainComponent" text, "outputComponent" text, "kitComponents" text, "teacherMaterials" text, "learnerMaterials" text, "introText" text, "teachingPoints" text, "classActivities" text, "infographicManual" text, "engineeringProblem" text, "engineeringInput" text, "engineeringBrain" text, "engineeringOutput" text, "engineeringSolution" text, "homeChallenge" text, "assessmentType" character varying, "assessmentScale" character varying, "assessmentDimension" character varying, "assessmentEvidenceType" character varying, "assessmentQuestions" text, "observationChecklist" text, "portfolioDescription" text, "portfolioLabel" character varying, "coachingNotes" text, "progressPercent" integer NOT NULL DEFAULT '0', "tools" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "stepNumber" integer NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f966f3e23aad73b7c871daae24b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "classId" uuid NOT NULL, "teacherId" uuid NOT NULL, "startedAt" TIMESTAMP NOT NULL, "pausedDurationSeconds" integer NOT NULL DEFAULT '0', "completedAt" TIMESTAMP, "elapsedSeconds" integer NOT NULL DEFAULT '0', "reflection" character varying, "sentiment" character varying, "syncStatus" character varying NOT NULL DEFAULT 'syncing', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07c712bd1808a8a198d9ff2ef38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying, "fileName" character varying, "duration" character varying, "category" character varying, "order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c89a6a9b6d788de58bf5348ee35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lesson_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "title" character varying NOT NULL, "orderIndex" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1a41dd565d17956addeb34ee62b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homeworks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "classId" uuid NOT NULL, "title" character varying NOT NULL, "instructions" text, "dueDate" date, "publishedAt" TIMESTAMP, "status" character varying NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b14704fd42638206031612722de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "homeworkId" uuid NOT NULL, "learnerId" uuid NOT NULL, "submittedAt" TIMESTAMP, "fileType" character varying, "fileUrl" character varying, "fileName" character varying, "fileSizeMb" numeric, "reviewStatus" character varying NOT NULL DEFAULT 'pending', "feedbackPublishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4c570ffb4ce1a34b63afa9d1b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "homework_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "submissionId" uuid NOT NULL, "senderType" character varying NOT NULL, "senderName" character varying, "body" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a5527f3516e94bd8d7cc2f70f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evidence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonId" uuid NOT NULL, "classId" uuid NOT NULL, "teacherId" uuid NOT NULL, "mediaType" character varying NOT NULL, "fileUrl" character varying, "consentChecked" boolean NOT NULL DEFAULT false, "syncStatus" character varying NOT NULL DEFAULT 'queued', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b864cb5d49854f89917fc0b44b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evidence_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "evidenceId" uuid NOT NULL, "learnerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3df046d2309a24249872379e690" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "curriculum_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "version" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'draft', "publishedAt" TIMESTAMP, "isImmutable" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dca2425faf5e38d8ab1953ce400" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "gradeLevel" character varying, "subject" character varying, "schoolId" uuid NOT NULL, "teacherId" uuid, "learnerCount" integer NOT NULL DEFAULT '0', "curriculumCoveragePercent" numeric NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certificates" ("id" character varying NOT NULL, "learnerId" uuid NOT NULL, "course" character varying, "term" character varying, "school" character varying, "issueDate" date, "verifiedId" character varying, "templateHtml" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e4c7e31e2144300bea7d89eb165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bulk_imports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'template', "totalRows" integer NOT NULL DEFAULT '0', "validRows" integer NOT NULL DEFAULT '0', "errorCount" integer NOT NULL DEFAULT '0', "columnMapping" text, "errors" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_315f37bb12f9f11d0bb1ddee5ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "iconType" character varying, "triggerRule" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "badge_awards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "badgeId" uuid NOT NULL, "learnerId" uuid NOT NULL, "linkedProjectId" uuid, "awardedAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5fa679a182a2bd25a7be1ab1e6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event" character varying NOT NULL, "actorId" character varying, "actorName" character varying, "target" character varying, "result" character varying, "timestamp" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lessonSessionId" uuid NOT NULL, "learnerId" uuid NOT NULL, "classId" uuid NOT NULL, "date" date NOT NULL, "status" character varying NOT NULL, "markedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "learnerId" uuid NOT NULL, "lessonId" uuid NOT NULL, "lessonSessionId" uuid, "score" integer NOT NULL, "savedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "announcements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "message" text NOT NULL, "audience" character varying NOT NULL, "schoolId" uuid, "classId" uuid, "postedById" uuid NOT NULL, "postedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b3ad760876ff2e19d58e05dc8b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "lessonId" uuid, "role" character varying NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a390434d4a515ba18a41bc996c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "schoolId" uuid, "modelTier" character varying NOT NULL DEFAULT 'small', "monthlyCallCap" integer NOT NULL DEFAULT '1000', "callsThisMonth" integer NOT NULL DEFAULT '0', "estimatedSpend" numeric NOT NULL DEFAULT '0', "reportsPublished" integer NOT NULL DEFAULT '0', "teacherReviewRate" numeric NOT NULL DEFAULT '0', "requireTeacherReview" boolean NOT NULL DEFAULT true, "voiceToTextEnabled" boolean NOT NULL DEFAULT false, "lessonAssistantScope" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_d567c0772a69a2b0f9b263f7f9" UNIQUE ("schoolId"), CONSTRAINT "PK_e062638208222edc23b70e8c31b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_435e192698a6b7d10849295643d" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_9dc06040dc3d191260c4e21150d" FOREIGN KEY ("curriculumVersionId") REFERENCES "curriculum_versions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sync_queue" ADD CONSTRAINT "FK_5d041d869350ce5d4c07da119d8" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schools" ADD CONSTRAINT "FK_a31583c1fe0561969edda0a126e" FOREIGN KEY ("curriculumVersionId") REFERENCES "curriculum_versions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "school_reports" ADD CONSTRAINT "FK_9595af3a81273d5ea98d75ea6ce" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_f3e2cf105f54351c1f3cdca5abd" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_690c6e1138decd36e121ac5ce25" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "progress_reports" ADD CONSTRAINT "FK_59095d1c16cc843362db90a2fff" FOREIGN KEY ("childId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_children" ADD CONSTRAINT "FK_ef3f10e877846e162781086e846" FOREIGN KEY ("parentId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parent_children" ADD CONSTRAINT "FK_e3bbd2e9386b2f512e61625d62f" FOREIGN KEY ("childId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media_library" ADD CONSTRAINT "FK_384b10d6ae6b6b4d565393bc796" FOREIGN KEY ("unitId") REFERENCES "units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" ADD CONSTRAINT "FK_540247177fdb4d2dbd7be03c586" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" ADD CONSTRAINT "FK_c64fe9af1f60f38adc6d15de05c" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" ADD CONSTRAINT "FK_31c6bd429f65352441703b2be10" FOREIGN KEY ("dimensionId") REFERENCES "lqs_dimensions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_7c9fe457707c44ae26910acf6c5" FOREIGN KEY ("unitId") REFERENCES "units"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_steps" ADD CONSTRAINT "FK_2b43abc6514e55767ed4e374309" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" ADD CONSTRAINT "FK_d969da930bf78b0f7186682ae2b" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" ADD CONSTRAINT "FK_954239fc80ea3e1805ed83939d3" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" ADD CONSTRAINT "FK_9d7bc86f3271790c90701a87ecd" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_media" ADD CONSTRAINT "FK_3929ad9f3bf4d422fcb00b97d6f" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_activities" ADD CONSTRAINT "FK_42526d38aa3e865f98fa66d3a74" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homeworks" ADD CONSTRAINT "FK_32b6be48a3f64c89192830fdc73" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homeworks" ADD CONSTRAINT "FK_ec0007459fc4131dc48695c1c19" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD CONSTRAINT "FK_6802466f772052fbe84d3f8b888" FOREIGN KEY ("homeworkId") REFERENCES "homeworks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD CONSTRAINT "FK_3367ab83ce03fe19c7b9c7b00fc" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "homework_messages" ADD CONSTRAINT "FK_03aad62ba6bd7cf9d61b2119613" FOREIGN KEY ("submissionId") REFERENCES "homework_submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence" ADD CONSTRAINT "FK_ac9bbe2c21ea4bc9461b143be06" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence" ADD CONSTRAINT "FK_28f0eaf0dbf1cd61dc21a3cefe9" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence" ADD CONSTRAINT "FK_c39bb1fea464bef662bba4d645b" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence_tags" ADD CONSTRAINT "FK_d8a06b8afbc4a3c8b78b5c2d481" FOREIGN KEY ("evidenceId") REFERENCES "evidence"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence_tags" ADD CONSTRAINT "FK_a17e6339829b9bed59a3d046dc6" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_17d36b6f6a79669ba76b671ac72" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_04a6f6d8033c1c285b55ca15447" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bulk_imports" ADD CONSTRAINT "FK_9302089528bfdbc3034468ddbdb" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "badge_awards" ADD CONSTRAINT "FK_a5a049ae01b20acc7892e268b78" FOREIGN KEY ("badgeId") REFERENCES "badges"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "badge_awards" ADD CONSTRAINT "FK_de8754fd6c5597ede8f1a68301b" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "badge_awards" ADD CONSTRAINT "FK_a76722a18466647b0095fd26658" FOREIGN KEY ("linkedProjectId") REFERENCES "projects"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_ed3a37750633d45453ab5363974" FOREIGN KEY ("lessonSessionId") REFERENCES "lesson_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_d38581c6dfa83b7378ef1e0b148" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance" ADD CONSTRAINT "FK_af129543ec010c822cb6f0254b5" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_e0bb5804e4adce772a54d363626" FOREIGN KEY ("learnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_c0c858dfd225249fe292a2319e9" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessments" ADD CONSTRAINT "FK_386f3348c7e10fcf4149f5863b9" FOREIGN KEY ("lessonSessionId") REFERENCES "lesson_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_e49fae0393356ec4eb6f12e5d91" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_c22586dee42cd7d0b57d3ab5893" FOREIGN KEY ("classId") REFERENCES "classes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "announcements" ADD CONSTRAINT "FK_9239a03f192ebbe2decbb1eaa43" FOREIGN KEY ("postedById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_messages" ADD CONSTRAINT "FK_a3dcab02fc150142063a577b77a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_messages" ADD CONSTRAINT "FK_98ff7fdf80c42d478343b96ff5c" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_configs" ADD CONSTRAINT "FK_d567c0772a69a2b0f9b263f7f9c" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_configs" DROP CONSTRAINT "FK_d567c0772a69a2b0f9b263f7f9c"`);
        await queryRunner.query(`ALTER TABLE "ai_messages" DROP CONSTRAINT "FK_98ff7fdf80c42d478343b96ff5c"`);
        await queryRunner.query(`ALTER TABLE "ai_messages" DROP CONSTRAINT "FK_a3dcab02fc150142063a577b77a"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_9239a03f192ebbe2decbb1eaa43"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_c22586dee42cd7d0b57d3ab5893"`);
        await queryRunner.query(`ALTER TABLE "announcements" DROP CONSTRAINT "FK_e49fae0393356ec4eb6f12e5d91"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_386f3348c7e10fcf4149f5863b9"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_c0c858dfd225249fe292a2319e9"`);
        await queryRunner.query(`ALTER TABLE "assessments" DROP CONSTRAINT "FK_e0bb5804e4adce772a54d363626"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_af129543ec010c822cb6f0254b5"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_d38581c6dfa83b7378ef1e0b148"`);
        await queryRunner.query(`ALTER TABLE "attendance" DROP CONSTRAINT "FK_ed3a37750633d45453ab5363974"`);
        await queryRunner.query(`ALTER TABLE "badge_awards" DROP CONSTRAINT "FK_a76722a18466647b0095fd26658"`);
        await queryRunner.query(`ALTER TABLE "badge_awards" DROP CONSTRAINT "FK_de8754fd6c5597ede8f1a68301b"`);
        await queryRunner.query(`ALTER TABLE "badge_awards" DROP CONSTRAINT "FK_a5a049ae01b20acc7892e268b78"`);
        await queryRunner.query(`ALTER TABLE "bulk_imports" DROP CONSTRAINT "FK_9302089528bfdbc3034468ddbdb"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_04a6f6d8033c1c285b55ca15447"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_4b7ac7a7eb91f3e04229c7c0b6f"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_17d36b6f6a79669ba76b671ac72"`);
        await queryRunner.query(`ALTER TABLE "evidence_tags" DROP CONSTRAINT "FK_a17e6339829b9bed59a3d046dc6"`);
        await queryRunner.query(`ALTER TABLE "evidence_tags" DROP CONSTRAINT "FK_d8a06b8afbc4a3c8b78b5c2d481"`);
        await queryRunner.query(`ALTER TABLE "evidence" DROP CONSTRAINT "FK_c39bb1fea464bef662bba4d645b"`);
        await queryRunner.query(`ALTER TABLE "evidence" DROP CONSTRAINT "FK_28f0eaf0dbf1cd61dc21a3cefe9"`);
        await queryRunner.query(`ALTER TABLE "evidence" DROP CONSTRAINT "FK_ac9bbe2c21ea4bc9461b143be06"`);
        await queryRunner.query(`ALTER TABLE "homework_messages" DROP CONSTRAINT "FK_03aad62ba6bd7cf9d61b2119613"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP CONSTRAINT "FK_3367ab83ce03fe19c7b9c7b00fc"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP CONSTRAINT "FK_6802466f772052fbe84d3f8b888"`);
        await queryRunner.query(`ALTER TABLE "homeworks" DROP CONSTRAINT "FK_ec0007459fc4131dc48695c1c19"`);
        await queryRunner.query(`ALTER TABLE "homeworks" DROP CONSTRAINT "FK_32b6be48a3f64c89192830fdc73"`);
        await queryRunner.query(`ALTER TABLE "lesson_activities" DROP CONSTRAINT "FK_42526d38aa3e865f98fa66d3a74"`);
        await queryRunner.query(`ALTER TABLE "lesson_media" DROP CONSTRAINT "FK_3929ad9f3bf4d422fcb00b97d6f"`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" DROP CONSTRAINT "FK_9d7bc86f3271790c90701a87ecd"`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" DROP CONSTRAINT "FK_954239fc80ea3e1805ed83939d3"`);
        await queryRunner.query(`ALTER TABLE "lesson_sessions" DROP CONSTRAINT "FK_d969da930bf78b0f7186682ae2b"`);
        await queryRunner.query(`ALTER TABLE "lesson_steps" DROP CONSTRAINT "FK_2b43abc6514e55767ed4e374309"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_7c9fe457707c44ae26910acf6c5"`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" DROP CONSTRAINT "FK_31c6bd429f65352441703b2be10"`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" DROP CONSTRAINT "FK_c64fe9af1f60f38adc6d15de05c"`);
        await queryRunner.query(`ALTER TABLE "lqs_scores" DROP CONSTRAINT "FK_540247177fdb4d2dbd7be03c586"`);
        await queryRunner.query(`ALTER TABLE "media_library" DROP CONSTRAINT "FK_384b10d6ae6b6b4d565393bc796"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "parent_children" DROP CONSTRAINT "FK_e3bbd2e9386b2f512e61625d62f"`);
        await queryRunner.query(`ALTER TABLE "parent_children" DROP CONSTRAINT "FK_ef3f10e877846e162781086e846"`);
        await queryRunner.query(`ALTER TABLE "progress_reports" DROP CONSTRAINT "FK_59095d1c16cc843362db90a2fff"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_690c6e1138decd36e121ac5ce25"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_f3e2cf105f54351c1f3cdca5abd"`);
        await queryRunner.query(`ALTER TABLE "school_reports" DROP CONSTRAINT "FK_9595af3a81273d5ea98d75ea6ce"`);
        await queryRunner.query(`ALTER TABLE "schools" DROP CONSTRAINT "FK_a31583c1fe0561969edda0a126e"`);
        await queryRunner.query(`ALTER TABLE "sync_queue" DROP CONSTRAINT "FK_5d041d869350ce5d4c07da119d8"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_9dc06040dc3d191260c4e21150d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_435e192698a6b7d10849295643d"`);
        await queryRunner.query(`DROP TABLE "ai_configs"`);
        await queryRunner.query(`DROP TABLE "ai_messages"`);
        await queryRunner.query(`DROP TABLE "announcements"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "badge_awards"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP TABLE "bulk_imports"`);
        await queryRunner.query(`DROP TABLE "certificates"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "curriculum_versions"`);
        await queryRunner.query(`DROP TABLE "evidence_tags"`);
        await queryRunner.query(`DROP TABLE "evidence"`);
        await queryRunner.query(`DROP TABLE "homework_messages"`);
        await queryRunner.query(`DROP TABLE "homework_submissions"`);
        await queryRunner.query(`DROP TABLE "homeworks"`);
        await queryRunner.query(`DROP TABLE "lesson_activities"`);
        await queryRunner.query(`DROP TABLE "lesson_media"`);
        await queryRunner.query(`DROP TABLE "lesson_sessions"`);
        await queryRunner.query(`DROP TABLE "lesson_steps"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP TABLE "lqs_dimensions"`);
        await queryRunner.query(`DROP TABLE "lqs_scores"`);
        await queryRunner.query(`DROP TABLE "media_library"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "parent_children"`);
        await queryRunner.query(`DROP TABLE "progress_reports"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "school_reports"`);
        await queryRunner.query(`DROP TABLE "schools"`);
        await queryRunner.query(`DROP TABLE "sync_queue"`);
        await queryRunner.query(`DROP TABLE "units"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
