server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Small assets and long-cache for images/fonts references
    location = / {
        return 302 /design/index.html;
    }

    location /design/ {
        try_files $uri $uri/ =404;
    }

    # Health check
    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        return 302 /design/index.html;
    }
}
